import 'dart:ui';

/// One hole's realistic map assets. All coordinates are normalized 0..1 in
/// image space (x right, y down) — the image is drawn full-bleed in the
/// 3:4 map viewport, so these map directly onto taps and shot storage.
class HoleMapAsset {
  final int par;
  final String map;
  final String mask;

  /// Tee-box and pin positions in normalized 0..1 image space. Drawn at
  /// runtime (crisp at any size) — never rely on baked-in markers.
  final Offset tee;
  final Offset pin;

  /// Where the rendered geometry came from: 'osm', 'mixed', or
  /// 'synthetic'. Informational only — rendering quality, not behavior.
  final String source;

  const HoleMapAsset({
    required this.par,
    required this.map,
    required this.mask,
    required this.tee,
    required this.pin,
    this.source = 'synthetic',
  });
}

/// Generated by tools/hole-maps/render.py — do not hand-edit.
///
/// FIXTURE — hand-written placeholder data so Phase 3 (app integration)
/// can be built and tested before the real rendered assets land. The
/// rendering step will overwrite this file with the generated version
/// (same format, same path). Only Yale holes 1-2 exist here.
const holeMapManifest = <String, Map<int, HoleMapAsset>>{
  'Yale Golf Course': {
    1: HoleMapAsset(
      par: 4,
      map: 'assets/hole_maps/yale-golf-course/1.jpg',
      mask: 'assets/hole_maps/yale-golf-course/1_mask.png',
      tee: Offset(0.5, 0.88),
      pin: Offset(0.5, 0.12),
      source: 'osm',
    ),
    2: HoleMapAsset(
      par: 3,
      map: 'assets/hole_maps/yale-golf-course/2.jpg',
      mask: 'assets/hole_maps/yale-golf-course/2_mask.png',
      tee: Offset(0.42, 0.86),
      pin: Offset(0.58, 0.18),
    ),
  },
};
